[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.1", features = ["derive"] }
bindgen = "0.64.0"
aya-tool = { git = "https://github.com/aya-rs/aya", branch = "main" }
