/* automatically generated by rust-bindgen 0.64.0 */

pub type __socklen_t = ::aya_bpf::cty::c_uint;
pub type socklen_t = __socklen_t;
pub type sa_family_t = ::aya_bpf::cty::c_ushort;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr {
    pub sa_family: sa_family_t,
    pub sa_data: [::aya_bpf::cty::c_char; 14usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct addrinfo {
    pub ai_flags: ::aya_bpf::cty::c_int,
    pub ai_family: ::aya_bpf::cty::c_int,
    pub ai_socktype: ::aya_bpf::cty::c_int,
    pub ai_protocol: ::aya_bpf::cty::c_int,
    pub ai_addrlen: socklen_t,
    pub ai_addr: *mut sockaddr,
    pub ai_canonname: *mut ::aya_bpf::cty::c_char,
    pub ai_next: *mut addrinfo,
}
